Added dbus-send query for playback status (spotify)
erikw/tmux-powerline pull request #289
Opened 2022-07-30 05:27 UTC by HalbardHobby

2022-07-30 05:33 UTC, erikw commented
Thank you! Just one thing to fix

2022-07-31 19:22 UTC, HalbardHobby commented
Just tell me to fix the PR.

2022-08-03 15:45 UTC, HalbardHobby commented
Still waiting the fix request 😅😅😅

2022-08-03 15:51 UTC, erikw commented
Please go ahead and fix it =)

2022-08-03 16:12 UTC, HalbardHobby commented
I meant that you didn't tell what I need to fix 😅

2022-08-03 16:34 UTC, erikw requested changes

2022-08-03 16:35 UTC, erikw commented
Ah now your comment makes more sense. I'm sorry, I had forgotten to publish my comment, it was still in draft mode haha

2022-08-03 16:42 UTC, HalbardHobby commented on segments/now_playing.sh
> +# Music player to use. Can be any of {audacious, banshee, cmus, itunes, lastfm, mocp, mpd, mpd_simple, pithos, playerctl, rdio, rhythmbox, spotify, spotify_wine, file}.
Moved back to place in d95c27e 😁

2022-08-03 16:43 UTC, HalbardHobby commented
No worries, already fixed the issue.

2022-08-03 16:46 UTC, merged