Created a new segment to track Air Quality "Air"
erikw/tmux-powerline pull request #354
Opened 2024-01-21 12:48 UTC by gavink97

Air allows users to track air quality in a give location via the Open Weather API.

It utilizes US AQI which is the US standard to measure Air quality and returns different colors + symbols for each index level.

Users can use the TMUX_POWERLINE_SEG_AIR_COLOR variable to have the segment change colors as the Air Quality goes between different index levels.

2024-01-22 13:25 UTC, erikw requested changes
Wow cool! Just ones thing to fix

2024-01-22 13:25 UTC, erikw commented on lib/headers.sh
> +
Segments should not be sourced here. Please remove and verify that the segment still works :).

2024-01-22 14:49 UTC, gavink97 commented
> Wow cool! Just ones thing to fix

Okay I fixed it 👍🏼

2024-01-23 00:50 UTC, erikw approved these changes

2024-01-23 01:05 UTC, merged

2024-01-23 01:05 UTC, erikw commented
Thx