Update mac os notifcations segment to work with sonoma
erikw/tmux-powerline pull request #365
Opened 2024-03-23 23:45 UTC by ryanfabela

Also updated id for messages and added slack id to help out others

2024-03-23 23:46 UTC, ryanfabela commented
tested this locally on Sonoma (Version 14.0 (23A344))

2024-03-24 02:09 UTC, erikw commented on segments/macos_notification_count.sh
> +TMUX_POWERLINE_SEG_MACOS_NOTIFICATION_COUNT_APPIDS_DEFAULT="118 51"
Let’s not add Slack to the default, not everyone has this app.

2024-03-24 02:10 UTC, erikw requested changes
Thanks. Just one small fix

2024-03-24 02:16 UTC, ryanfabela commented
Understoon. Makes total sense. Made the change, thank you

2024-03-24 02:17 UTC, merged