Fix issue with air quality rendering a white background.
erikw/tmux-powerline pull request #397
Opened 2024-04-07 18:41 UTC by shyce

This pull request fixes the default and bubble theme so that including `air` works properly by default.

- `air_color.sh` now exports TMUX_POWERLINE_SEG_AIR_COLOR
- Themes now source `air_color.sh`. I think there should be a standard interface for segments to provide suggested colors in the future but this works fine for now.
- Fixed up some extra spaces after comments.

2024-04-07 19:29 UTC, xx4h commented
Hi @shyce, the way i see it, `air_color.sh` should not be a segment at all. Overriding the color for a specific symbol of a segment should be done directly in the segment.
Something like we did here:
https://github.com/erikw/tmux-powerline/blob/fd480c2d6ae5e24a18589c4ef8e3685bc576e186/segments/vcs_branch.sh#L9
and then use it like this:
https://github.com/erikw/tmux-powerline/blob/fd480c2d6ae5e24a18589c4ef8e3685bc576e186/segments/vcs_branch.sh#L68

What do you think? Do you want to go for this refactor?

2024-04-07 19:32 UTC, shyce commented
Yeah let me take a look at this tonight after a bit of a break from the pc. I didn't like it either, just didn't want to commit a big change as a new contributor. Thanks for the feedback!

2024-04-07 19:42 UTC, xx4h commented
> Yeah let me take a look at this tonight after a bit of a break from the pc. I didn't like it either, just didn't want to commit a big change as a new contributor. Thanks for the feedback!

Cool, appreciate it! Let me know if you have any questions.

2024-04-08 17:23 UTC, shyce commented
I gave this a shot last night and it looks like it will need a bit more work. No modules are using #[bg=] currently because it doesn't color the powerline symbols as well, since it allows you to have multiple background colors in one echo. I'm still thinking about the best way to do this while adhering to the previous theme api.

I didn't want to change the way #[bg=] works because it might break peoples custom themes.

2024-04-08 20:17 UTC, xx4h commented
Oh, i guess i got i wrong yesterday. So it is not about the color for the symbol, it's about the color of the whole segment, right? And based on the air-quality the color of the segment should change?

2024-04-08 20:45 UTC, xx4h requested changes
In this case i'd prefer not to source the segment in the theme, but rather fix the `air_color.sh` so it will echo back the color, so it can be used as expected in the theme files. I agree that this is still not a very good solution, but i guess it makes more sense to consider those kind of requirements (e.g. control the background color for the segment from within the segment itself) for a more general refactor.

2024-04-08 20:45 UTC, xx4h commented on segments/air_color.sh
> +export TMUX_POWERLINE_SEG_AIR_COLOR="${TMUX_POWERLINE_SEG_AIR_COLOR:-'37'}"
```suggestion
echo "${TMUX_POWERLINE_SEG_AIR_COLOR:-'37'}"
```

2024-04-08 20:45 UTC, xx4h commented on themes/bubble.sh
> +source ${TMUX_POWERLINE_DIR_HOME}/segments/air_color.sh
```suggestion
TMUX_POWERLINE_SEG_AIR_COLOR=$("${TMUX_POWERLINE_DIR_HOME}/segments/air_color.sh")
```

2024-04-08 20:45 UTC, xx4h commented on themes/default.sh
> +source ${TMUX_POWERLINE_DIR_HOME}/segments/air_color.sh
```suggestion
TMUX_POWERLINE_SEG_AIR_COLOR=$("${TMUX_POWERLINE_DIR_HOME}/segments/air_color.sh")
```

2024-04-08 20:45 UTC, xx4h commented on themes/bubble.sh
> +    #"air ${TMUX_POWERLINE_SEG_AIR_COLOR} $thm_bg" \
Looks like here is still something wrong with the tabs?

2024-04-08 20:46 UTC, shyce commented
Yeah the air quality index changes the whole segment color based on the quality of the air I guess. I tried the echo approach instead of sourcing and for some reason, the output would not concat to the string. No idea why.

2024-04-08 20:51 UTC, shyce commented
I just tried again, and I guess I made a typo because it did work this time. Let me update it.

2024-04-08 21:02 UTC, shyce commented
Stand by, I guess my editor tab stops do not match the project.

2024-04-08 21:11 UTC, shyce commented
That's much cleaner, thanks. I'll try again at my dynamic approach that lets each segment setup their own colors in a later PR.

2024-04-09 07:29 UTC, xx4h commented on segments/air_color.sh
> +echo $TMUX_POWERLINE_SEG_AIR_COLOR
```suggestion
echo "${TMUX_POWERLINE_SEG_AIR_COLOR:-'37'}"
```

2024-04-09 07:34 UTC, xx4h commented on segments/air_color.sh
> +echo $TMUX_POWERLINE_SEG_AIR_COLOR
Re-assign unnecessary

2024-04-09 16:24 UTC, merged