Add an optional log to the `now_playing` segment
erikw/tmux-powerline pull request #424
Opened 2024-05-02 18:45 UTC by IngoMeyer441

2024-05-05 09:51 UTC, xx4h commented
Hi, thanks for contributing! Do you mind fixing the shell_shfmt and bash linter errors?

2024-05-05 21:06 UTC, IngoMeyer441 commented
@xx4h Thanks for your response. Should all be ok now :smiley:.

2024-05-06 09:08 UTC, xx4h requested changes

2024-05-06 10:57 UTC, IngoMeyer441 commented on segments/now_playing.sh
> +		if [[ -n "$TMUX_POWERLINE_SEG_NOW_PLAYING_TRACK_LOG_FILEPATH" && -n "$TMUX_POWERLINE_SEG_NOW_PLAYING_TRACK_LOG_MAX_ENTRIES" ]]; then
I think this is a good idea. I have added the bool flag and a small helper function to a new lib file to check the flag value (I hope this is ok).

2024-05-06 13:23 UTC, xx4h commented on segments/now_playing.sh
> +		if [[ -n "$TMUX_POWERLINE_SEG_NOW_PLAYING_TRACK_LOG_FILEPATH" && -n "$TMUX_POWERLINE_SEG_NOW_PLAYING_TRACK_LOG_MAX_ENTRIES" ]]; then
> I think this is a good idea. I have added the bool flag and a small helper function to a new lib file to check the flag value (I hope this is ok).

yeah, that's great, i like the `lib/util.sh`.

2024-05-06 13:29 UTC, xx4h approved these changes

2024-05-06 13:35 UTC, merged